'''
Generated by GhatGPT
description: 处理文本文件，将连续两行及以上的空行替换为'※※※'，并输出到新文件中。
'''
import sys
import os

def process_file(file_path):
    try:
        # 读取文件内容
        with open(file_path, 'r', encoding='utf-8') as file:
            lines = file.readlines()

        processed_lines = []
        empty_line_count = 0

        for line in lines:
            # 去掉每行两端的空白字符
            stripped_line = line.strip()

            if not stripped_line:  # 空行
                empty_line_count += 1
            else:
                if empty_line_count >= 2:
                    # 将连续两行及以上的空行替换为'※※※'
                    processed_lines.append('\t※※※\n')
                empty_line_count = 0
                processed_lines.append('\t' + stripped_line + '\n')

        # 如果文件末尾有空行，也需要处理
        if empty_line_count >= 2:
            processed_lines.append('※※※\n')

        # 构造输出文件名
        output_file = f"{os.path.splitext(file_path)[0]}_completed.txt"

        # 写入处理后的内容
        with open(output_file, 'w', encoding='utf-8') as file:
            file.writelines(processed_lines)

        print(f"处理完成！输出文件名：{output_file}")
    except Exception as e:
        print(f"发生错误：{e}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("用法: python <模块名>.py <文件名>")
    else:
        process_file(sys.argv[1])
